; PlatformIO Project Configuration File
;
; Sistema Modbus RTU Mestre/Escravo com STM32F103C8
; Usar: pio run -e master  (para compilar mestre)
; Usar: pio run -e slave   (para compilar escravo)

[platformio]
default_envs = master, slave

[env]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
monitor_speed = 115200
upload_protocol = serial
; Habilita Serial1 (USART1 nos pinos PA9/PA10) e Serial USB para logs
build_flags =
    -D ENABLE_HWSERIAL1
    -D PIN_SERIAL1_TX=PA9
    -D PIN_SERIAL1_RX=PA10
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC

; Firmware do MESTRE
[env:master]
build_src_filter = +<master/>

; Firmware do ESCRAVO
[env:slave]
build_src_filter = +<slave/>
